### ISSUE TITLE
Invalid sed command in makefile

### ISSUE THREAD

**Issue by yegle** [b-k/py1040#6]
gsed is the GNU sed, sed is the one comes with OS X.

```
$ sed '$$a)'
sed: 1: "$$a)": invalid command code $
$ gsed '$$a)'
gsed: -e expression #1, char 2: unknown command: `$'
```

**Comment by b-k** [comment]
`sed '$a)'` should add a single end-paren at the end of the file [`$` is sedspeak for end-of-file]. Because this is in a makefile, I have to write `$$` so the shell spawned by `make` will see a single `$`.

That is, I really thought this was POSIX-standard, and am surprised that it failed. I don't have a mac here, so if you have suggestions/pull requests for a POSIX standard means of adding an end-paren at the end of a file, I'm all ears.

**Comment by JHFreeman** [comment]
for POSIX-standard sed on OS X, you have to build it from source or install it via brew. If installed from brew it is 'gsed'

edit: the package in brew is gnu-sed

**Comment by witeshadow** [comment]
I had this issue on Ubuntu too.
